<ul class="navbar-nav">
    <?php $count = 0 ?>
    <?php foreach ($this->container as $page): ?>
        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if( ! $hasChildren): ?>
            <li class="nav-item<?php if($page->isActive()) echo ' active'?>">
                <a class="nav-link" href="<?php echo $page->getHref() ?>">
                    <?php echo $this->translate($page->getLabel()) ?>
                    <?php if($page->isActive()) echo '<span class="sr-only"> (current)</span>'?>
                </a>
            </li>
        <?php else: ?>
            <li class="nav-item dropdown<?php if($page->isActive()) echo ' active'; ?>">
                <a href="<?php echo $page->getHref() ?>" class="nav-link dropdown-toggle" id="navbarDropdown_<?php echo $count ?>" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <?php echo $this->translate($page->getLabel()) ?>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown_<?php echo $count ?>">
                  <?php foreach($page->getPages() as $child): ?>
                      <?php if( ! $child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                        <a href="<?php echo $child->getHref() ?>" class="dropdown-item<?php if($child->isActive()) echo ' active'?>">
                            <?php echo $this->translate($child->getLabel()) ?>
                        </a>
                  <?php endforeach ?>
                </div>
            </li>
        <?php endif; ?>
        <?php $count++ ?>
    <?php endforeach; ?>
</ul>
